-- ============================================================================
-- NeuroChat ↔ Supabase schema
-- Run this ONCE in the Supabase dashboard → SQL editor.
--
-- All primary keys are UUIDs generated by the NeuroChat server itself, so the
-- local SQLite database and this cloud database share the exact same ids.
-- RLS is opened to the anon role (the publishable key) because login in this
-- demo app is username-only and handled by the NeuroChat server.
-- ============================================================================

-- ---------------------------------------------------------------- users -----
create table if not exists public.users (
    id          uuid primary key,
    username    text not null,
    lang        text not null default 'en',
    created_at  timestamptz not null default now(),
    last_seen   timestamptz
);

-- -------------------------------------------------------- conversations -----
create table if not exists public.conversations (
    id          uuid primary key,
    user_id     uuid references public.users(id) on delete cascade,
    title       text,
    lang        text default 'en',
    created_at  timestamptz not null default now()
);

-- ------------------------------------------------------------ messages -----
create table if not exists public.messages (
    id               uuid primary key,
    conversation_id  uuid not null references public.conversations(id) on delete cascade,
    role             text not null,          -- 'user' | 'assistant'
    content          text not null,
    source           text,                   -- neural | search | template | fallback
    confidence       real,
    lang             text default 'en',      -- detected language of the message
    created_at       timestamptz not null default now()
);

-- ---------------------------------------------------- training_samples -----
create table if not exists public.training_samples (
    id          uuid primary key,
    prompt      text not null,
    response    text not null,
    source      text,
    quality     integer default 0,           -- -1 (downvoted) .. +1 (upvoted)
    lang        text default 'en',
    created_at  timestamptz not null default now()
);

-- ------------------------------------------------- registered_datasets -----
create table if not exists public.registered_datasets (
    name        text primary key,
    hf_id       text not null,
    kind        text,
    rows        integer default 0,
    updated_at  timestamptz,
    synced_at   timestamptz not null default now()
);

-- ------------------------------------------------------------- indexes -----
create index if not exists idx_cloud_conversations_user  on public.conversations(user_id);
create index if not exists idx_cloud_messages_conv       on public.messages(conversation_id);
create index if not exists idx_cloud_messages_created    on public.messages(created_at);
create index if not exists idx_cloud_users_username      on public.users(username);
create index if not exists idx_cloud_samples_created     on public.training_samples(created_at);

-- ---------------------------------------------------------------- RLS ------
-- The server authenticates users itself (username-only demo login), so the
-- publishable key gets full access to these tables.
alter table public.users             enable row level security;
alter table public.conversations     enable row level security;
alter table public.messages          enable row level security;
alter table public.training_samples  enable row level security;
alter table public.registered_datasets enable row level security;

drop policy if exists "neurochat_anon_users"             on public.users;
drop policy if exists "neurochat_anon_conversations"     on public.conversations;
drop policy if exists "neurochat_anon_messages"          on public.messages;
drop policy if exists "neurochat_anon_training_samples"  on public.training_samples;
drop policy if exists "neurochat_anon_registered_datasets" on public.registered_datasets;

create policy "neurochat_anon_users"             on public.users             for all to anon using (true) with check (true);
create policy "neurochat_anon_conversations"     on public.conversations     for all to anon using (true) with check (true);
create policy "neurochat_anon_messages"          on public.messages          for all to anon using (true) with check (true);
create policy "neurochat_anon_training_samples"  on public.training_samples  for all to anon using (true) with check (true);
create policy "neurochat_anon_registered_datasets" on public.registered_datasets for all to anon using (true) with check (true);
