"""Minimal Supabase client over the REST (PostgREST) API.

Uses only `requests` (already a project dependency) — no SDK needed. Every
primary key is a UUID generated by the NeuroChat server, and pushes are
upserts (`?on_conflict=id` + `Prefer: resolution=merge-duplicates`), so the
sync engine is idempotent and safe to retry.
"""
from __future__ import annotations

from typing import Dict, List, Optional, Tuple

import requests

from app import config


class SupabaseError(RuntimeError):
    """Raised when Supabase returns a non-2xx response."""


class Supabase:
    def __init__(self) -> None:
        self.url = (config.SUPABASE_URL or "").rstrip("/")
        self.key = (config.SUPABASE_KEY or "").strip()
        self._session = requests.Session()
        if self.available:
            self._session.headers.update({
                "apikey": self.key,
                "Authorization": f"Bearer {self.key}",
                "Content-Type": "application/json",
            })

    @property
    def available(self) -> bool:
        return bool(self.url and self.key)

    def _url(self, table: str) -> str:
        return f"{self.url}/rest/v1/{table}"

    # ------------------------------------------------------------------ #
    def select(self, table: str, filters: Optional[Dict[str, str]] = None,
               order: Optional[str] = None, limit: Optional[int] = None,
               columns: str = "*") -> List[Dict]:
        """GET rows, e.g. select("messages", {"conversation_id": "eq.<uuid>"}, limit=50)."""
        params: Dict[str, str] = {"select": columns}
        if filters:
            params.update(filters)
        if order:
            params["order"] = order
        if limit:
            params["limit"] = str(limit)
        resp = self._session.get(self._url(table), params=params, timeout=10)
        if resp.status_code >= 400:
            raise SupabaseError(self._error(resp))
        return resp.json()

    def upsert(self, table: str, rows: List[Dict],
               conflict: str = "id") -> Tuple[bool, str]:
        """Insert-or-update rows (single POST per call). Returns (ok, error)."""
        headers = {"Prefer": "resolution=merge-duplicates,return=minimal"}
        resp = self._session.post(
            f"{self._url(table)}?on_conflict={conflict}",
            json=rows, headers=headers, timeout=15)
        if resp.status_code in (200, 201):
            return True, ""
        return False, self._error(resp)

    # ------------------------------------------------------------------ #
    @staticmethod
    def _error(resp: requests.Response) -> str:
        try:
            data = resp.json()
            msg = data.get("message") or data.get("error") or resp.text
        except Exception:
            msg = resp.text
        return f"supabase {resp.status_code}: {str(msg)[:200]}"

    def health(self) -> bool:
        """True if the REST endpoint answers at all (schema may still be missing)."""
        if not self.available:
            return False
        try:
            self._session.get(f"{self.url}/rest/v1/", timeout=6)
            return True
        except requests.RequestException:
            return False


client = Supabase()
